using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Nino.Generator.Metadata;
using Nino.Generator.Template;

namespace Nino.Generator.Common;

public class TypeConstGenerator(
    Dictionary<int, TypeInfoDto> typeInfoCache,
    string assemblyNamespace,
    NinoGraph ninoGraph,
    EquatableArray<NinoType> ninoTypes)
    : NinoCommonGenerator(typeInfoCache, assemblyNamespace, ninoGraph, ninoTypes)
{
    protected override void Generate(SourceProductionContext spc)
    {
        // get type full names from models (namespaces + type names)
        var serializableTypes = NinoTypes
            .Where(ninoType => ninoType.IsPolymorphic)
            .Select(type => type.TypeInfo)
            .Where(typeInfo => TypeInfoDtoExtensions.IsInstanceType(typeInfo))
            .ToList();

        var types = new StringBuilder();
        foreach (var typeInfo in serializableTypes)
        {
            string variableName = typeInfo.FullyQualifiedName.GetTypeConstName();
            types.AppendLine($"\t\t// {typeInfo.FullyQualifiedName}");
            types.AppendLine($"\t\tpublic const int {variableName} = {typeInfo.TypeId};");
        }

        var curNamespace = AssemblyNamespace;

        // generate code
        var code = $$"""
                     // <auto-generated/>
                     #nullable disable

                     using System;
                     using Nino.Core;
                     using System.Runtime.CompilerServices;

                     namespace {{curNamespace}}
                     {
                         public static class NinoTypeConst
                         {
                     {{types}}
                         }
                     }
                     """;

        spc.AddSource($"{curNamespace}.TypeConst.g.cs", code);
    }
}